CREATE TABLE IF NOT EXISTS "jobs" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"category" text NOT NULL,
	"code" text,
	"description" text NOT NULL,
	"type" text NOT NULL,
	"vacancy" numeric NOT NULL,
	"job_place" numeric NOT NULL,
	"deadline" date NOT NULL,
	"job_label" text NOT NULL,
	"num_of_experience" text NOT NULL,
	"salary_type" text NOT NULL,
	"currency" text NOT NULL,
	"salary_range" text NOT NULL,
	"street_address" text NOT NULL,
	"city" text NOT NULL,
	"zip_code" text NOT NULL,
	"country" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp
);
